// Code generaTed by fileb0x at "2018-09-02 23:38:39.719306216 +0500 +05 m=+0.056344016" from config file "fileb0x.yml" DO NOT EDIT.
// modified(2018-09-02 23:37:18.302802443 +0500 +05)
// original path: assets/src/html/admin/index.html

package assets

import (
  
  "os"
)

// FileAdminIndexHTML is "/admin/index.html"
var FileAdminIndexHTML = []byte("\x3c\x70\x3e\x49\x4e\x44\x45\x58\x20\x54\x41\x42\x3c\x2f\x70\x3e")

func init() {
  

  f, err := FS.OpenFile(CTX, "/admin/index.html", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
  if err != nil {
    panic(err)
  }

  
  _, err = f.Write(FileAdminIndexHTML)
  if err != nil {
    panic(err)
  }
  

  err = f.Close()
  if err != nil {
    panic(err)
  }
}

