// Code generaTed by fileb0x at "2018-09-03 00:17:58.776096028 +0500 +05 m=+0.014270846" from config file "fileb0x.yml" DO NOT EDIT.
// modified(2018-09-03 00:17:09.256561732 +0500 +05)
// original path: assets/src/html/admin/packages.html

package assets

import (
  
  "os"
)

// FileAdminPackagesHTML is "/admin/packages.html"
var FileAdminPackagesHTML = []byte("\x50\x41\x43\x4b\x41\x47\x45\x53\x20\x54\x41\x42")

func init() {
  

  f, err := FS.OpenFile(CTX, "/admin/packages.html", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
  if err != nil {
    panic(err)
  }

  
  _, err = f.Write(FileAdminPackagesHTML)
  if err != nil {
    panic(err)
  }
  

  err = f.Close()
  if err != nil {
    panic(err)
  }
}

